# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordWithTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=45)),
                ('word', models.CharField(default='', max_length=45, unique=True)),
            ],
        ),
    ]
