#!/usr/bin/python
# -*- coding: utf-8 -*-
POS_ABBREVATIONS = {
    'CC': 'Coordinating conjunction',
    'CD': 'Cardinal number',
    'DT': 'Determiner',
    'EX': 'Existential there',
    'FW': 'Foreign word',
    'IN': 'Preposition or subordinating conjunction',
    'JJ': 'Adjective',
    'JJR': 'Comparative Adjective',
    'JJS': 'Superlative Adjective',
    'LS': 'List item marker',
    'MD': 'Model',
    'NN': 'Singular or mass Noun',
    'NNS': 'Pural Noun',
    'NNP': 'Pural singular Noun',
    'NNPS': 'Pural plural Noun',
    'PDT': 'Predeterminer',
    'POS': 'Possessive ending',
    'PRP': 'Personal pronoun',
    'PRP$': 'Possessive pronoun',
    'RB': 'Adverb',
    'RBR': 'Comparative Adverb',
    'RBS': 'Superlative Adverb',
    'RP': 'Particle',
    'SYM': 'Symbol',
    'TO': 'to',
    'UH': 'Interjection',
    'VB': 'Verb (base form)',
    'VBD': 'Verb (past tense)',
    'VBG': 'Verb (present participle)',
    'VBN': 'Verb (past participle)',
    'VBP': 'Verb (non 3rd person singular present tense)',
    'VBZ': 'Verb (3rd person singular present tense)',
    'WDT': 'WH-determiner',
    'WP': 'WH-pronoun',
    'WP$': 'Possessive WH-pronoun',
    'WRB': 'Wh-adverb',
    }

			
